### ISSUE TITLE
Auth0.com script is dying with 500 error.

### ISSUE THREAD

**Issue by vpetkar** [auth0/auth0-logs-to-mixpanel#1]
The script dies with the following error on auth0.com. Not sure what's up, the setup goes smoothly.

``` javascript
result: Object
 scheduled_at: Mon Aug 01 2016 16:50:00 GMT-0400 (EDT)
 started_at: Mon Aug 01 2016 16:50:16 GMT-0400 (EDT)
 completed_at: Mon Aug 01 2016 16:50:17 GMT-0400 (EDT)
 type: "error"
▶headers: Object
 statusCode: 500
 error: null
 body: "{
  "code": 500,
  "error": "Script generated an unhandled asynchronous exception.",
  "details": "TypeError: Cannot read property 'event' of undefined",
  "name": "TypeError",
  "message": "Cannot read property 'event' of undefined",
  "stack": "TypeError: Cannot read property 'event' of undefined\n    at /data/neutun%2F24509c31d0837e6fddde3eef311579f1:153:48\n    at Array.map (native)\n    at /data/neutun%2F24509c31d0837e6fddde3eef311579f1:152:46\n    at /data/neutun%2F24509c31d0837e6fddde3eef311579f1:173:12\n    at fn (/data/node_modules/async/lib/async.js:746:34)\n    at /data/node_modules/async/lib/async.js:1213:16\n    at /data/node_modules/async/lib/async.js:166:37\n    at /data/node_modules/async/lib/async.js:706:43\n    at /data/node_modules/async/lib/async.js:167:37\n    at Immediate._onImmediate (/data/node_modules/async/lib/async.js:1206:34)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"
}"

```

**Comment by vpetkar** [comment]
Fixed the script by changing these lines, can make PR if interested. Just added conditional to check the event exists in the JSON before accessing the property.

Old:

``` javascript
              var mixpanelEvents = context.logs.map(function (log) {
                      var eventName = logTypes[log.type].event;
                    // TODO - consider setting the time to date in the underlying log file?
                    // log.time = log.date;
                    log.time = now;
                    log.distinct_id = 'auth0-logs';
                    return {
                      event: eventName,
                      properties: log
                    };
              });
```

New:

``` javascript
              var mixpanelEvents = context.logs.map(function (log) {
                  if(logTypes[log.type]) {
                      var eventName = logTypes[log.type].event;
                    // TODO - consider setting the time to date in the underlying log file?
                    // log.time = log.date;
                    log.time = now;
                    log.distinct_id = 'auth0-logs';
                    return {
                      event: eventName,
                      properties: log
                    };
                  } else {
                      return null;
                  }
              });
```

**Comment by vpetkar** [comment]
Nevermind, still broken. Seems to be too many errors in this.

**Comment by sgmeyer** [comment]
I think the problem is this is missing some events.  The extension currently has a static list of logTypes.  I pushed a new list of events today.  This seems to have fixed the issues I saw.
